[package]
name = "coordinator"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "coordinator"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

coordinator_integrity = { workspace = true } 

zome_utils.workspace = true
